#host
server.url=******
server.port=80

#\u73B0\u8D27\u57FA\u7840\u5E73\u53F0
spot.server.url=******
spot.server.port=80

jdbc.driver=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://******:3306/******?useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL
jdbc.user=******
jdbc.password=******

#redis
redis.nodes=******

#mongo_db:
mongo.host=******
mongo.port=27017
mongo.username=******
mongo.password=******
mongo.database=******
#adjust market
base_url=******
#adjust market
ip=******
port=80



